version: '3'

services:
  dev:
    restart: always
    image: raptor_armv6_img
    container_name: 'raptor_main'
    volumes:
      - ../../../src:/home/nomura/src
      - ../../../build:/home/nomura/build
      - ../../../bin:/home/nomura/bin
      - ../../../lib:/home/nomura/lib
      - ../../../script:/home/nomura/script
      - ../../../config:/usr/local/config
      - ../../../resource/thermal_zone0:/home/nomura/thermal_zone0
      - ../../../resource/image:/home/nomura/image
      - ../../../resource/msgs:/var/opt/msgs

    command: bash
    ports:
      - 5555:5555
    tty: true
