version: '3'

services:
  dev:
    restart: always
    image: snomura07/raptor_develop_img:latest
    environment:
      - TZ=Asia/Tokyo
      - DISPLAY=${DISPLAY}  # WSLのDISPLAY変数をコンテナに渡す

    container_name: 'raptor_dev'
    volumes:
      - ../../../src:/home/nomura/src
      - ../../../build:/home/nomura/build
      - ../../../bin:/home/nomura/bin
      - ../../../lib:/home/nomura/lib
      - ../../../script:/home/nomura/script
      - ../../../resource/thermal_zone0:/home/nomura/thermal_zone0
      - ../../../resource/image:/usr/local/image:rw
      - ../../../config:/usr/local/config:rw
      - ../../../log:/usr/local/log:rw
      - ../../../resource/msgs:/var/opt/msgs:rw

      - /tmp/.X11-unix:/tmp/.X11-unix  # X11ソケットを共有

    # command: bash
    command: >
      bash -c "
        qemu-arm -L /usr/arm-linux-gnueabi /home/nomura/bin/ProxyServer &
        qemu-arm -L /usr/arm-linux-gnueabi /home/nomura/bin/ImageDirKeeper &
        wait
        bash
      "
    networks:
      - raptorlink
    ports:
      - 5555:5555
    tty: true

networks:
  raptorlink:
    external: true
    name: "RaptorLink"
