version: '3'

services:
  dev:
    restart: always
    image: snomura07/raptor_develop_img:latest
    container_name: 'raptor_dev'
    volumes:
      - ../../../src:/home/nomura/src
      - ../../../build:/home/nomura/build
      - ../../../bin:/home/nomura/bin
      - ../../../lib:/home/nomura/lib
      - ../../../script:/home/nomura/script
      - ../../../resource/thermal_zone0:/home/nomura/thermal_zone0

      - ../../../resource/image:/usr/local/image:rw
      - ../../../config:/usr/local/config:rw
      - ../../../log:/usr/local/log:rw
      - ../../../resource/msgs:/var/opt/msgs:rw

    # command: bash
    command: >
      bash -c "
        qemu-arm -L /usr/arm-linux-gnueabi /home/nomura/bin/ProxyServer
        bash
      "
    ports:
      - 5555:5555
    tty: true
