---
all:
  vars:
    ansible_user: pi
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
  hosts:
    pi:
      ansible_host: 100.64.1.200
      ansible_python_interpreter: /usr/bin/python3
      ansible_port: 22
