- name: pi.
  hosts: pi
  become: yes

  vars:
    syncDest: /opt/raptor/

  tasks:
    - name: Synchronize bin
      synchronize:
        src: /home/snomura/workspace/raptor/raptor.main/bin
        dest: "{{ syncDest }}"
        checksum: yes
        times: no

    - name: Synchronize lib
      synchronize:
        src: /home/snomura/workspace/raptor/raptor.main/lib
        dest: "{{ syncDest }}"
        checksum: yes
        times: no
      become: yes

    - name: Synchronize config
      synchronize:
        src: /home/snomura/workspace/raptor/raptor.main/config
        dest: "{{ syncDest }}"
        checksum: yes
        times: no
      become: yes

    - name: Replace environment in env file
      ansible.builtin.replace:
        dest: "{{ syncDest }}/config/env"
        regexp: '^ENV=.*$'
        replace: 'ENV=raspberrypi'
      become: yes
