- name: pi.
  hosts: pi
  become: yes

  tasks:
    - name: Synchronize bin
      synchronize:
        src: /home/snomura/workspace/raptor/raptor.main/bin
        dest: /home/pi/
        checksum: yes
        times: no

    - name: Synchronize lib
      synchronize:
        src: /home/snomura/workspace/raptor/raptor.main/lib
        dest: /home/pi/
        checksum: yes
        times: no
      become: yes

    - name: Synchronize config
      synchronize:
        src: /home/snomura/workspace/raptor/raptor.main/config
        dest: /usr/local/
        checksum: yes
        times: no
      become: yes

    - name: Replace environment in env file
      ansible.builtin.replace:
        path: /usr/local/config/env
        regexp: '^ENV=.*$'
        replace: 'ENV=raspberrypi'
      become: yes
