version: '3'

services:
  dev:
    restart: always
    image: snomura07/raptor_release_img:latest
    environment:
      - TZ=Asia/Tokyo
    container_name: 'raptor_main'
    privileged: true
    devices:
      - /dev/gpiomem:/dev/gpiomem
      - /dev/video0:/dev/video0
      - /dev/serial0:/dev/serial0
      - /dev/ttyAMA0:/dev/ttyAMA0
    volumes:
      - ../../../src:/home/pi/src
      - ../../../build:/home/pi/build
      - ../../../bin:/usr/local/bin
      - ../../../lib:/usr/local/lib
      - ../../../script:/home/pi/script
      - ../../../resource/image:/usr/local/image:rw
      - ../../../config:/usr/local/config:rw
      - ../../../log:/usr/local/log:rw
      - ../../../resource/msgs:/var/opt/msgs:rw
      - /sys/class:/sys/class

    # command: bash
    command: >
      bash -c "
      chmod -R a+w /usr/local/log;
      chmod -R a+rw /dev/video0;
      /usr/local/bin/ProxyServer
      bash"
    ports:
      - 5555:5555
    tty: true
