version: '3'

services:
  dev:
    restart: always
    image: snomura07/raptor_release_img:latest
    environment:
      - TZ=Asia/Tokyo
    container_name: 'raptor_main'
    privileged: true
    devices:
      - /dev/gpiomem:/dev/gpiomem
      - /dev/video0:/dev/video0
      - /dev/serial0:/dev/serial0
      - /dev/ttyAMA0:/dev/ttyAMA0
    volumes:
      - ../../../src:/home/pi/src
      - ../../../build:/home/pi/build
      - ../../../bin:/opt/raptor/bin
      - ../../../lib:/opt/raptor/lib
      - ../../../script:/home/pi/script
      - ../../../resource/image:/opt/raptor/image:rw
      - ../../../config:/opt/raptor/config:rw
      - ../../../log:/opt/raptor/log:rw
      - ../../../resource/msgs:/var/opt/msgs:rw
      - /sys/class:/sys/class

    # command: bash
    command: >
      bash -c "
      chmod -R a+w /opt/raptor/log;
      chmod -R a+rw /dev/video0;
      /opt/raptor/bin/ProxyServer
      bash"
    ports:
      - 5555:5555
    tty: true
